name: Build-Test-Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"
    - cron: "0 10 * * *"

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    name: Making builds
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
