name: Build-Test-Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * *"
    - cron: "0 10 * * *"

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    name: Making builds
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge

  Test-job1:
    runs-on: ubuntu-latest
    name: Test1
    needs: Build-job
    if: github.ref != 'refs/heads/production'
    steps:
      - uses: actions/checkout@v1
      - name: Test1
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g jest
      - run: npm test

  Deploy-job:
    runs-on: ubuntu-latest
    needs: Test-job1
    name: Deployment
    steps:
      - uses: actions/checkout@v1
      - name: Surge Deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

  PostDeploy-Testing:
    runs-on: ubuntu-latest
    needs: Deploy-job
    name: Curl-testing
    steps:
      - uses: actions/checkout@v1
      - name: Curl-testing
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: sudo apt install curl
      - run: curl -Is http://www.google.com | head -n 1
